name: knn-memory-clipcap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip=23.0.1
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pip:
    - ruff
    - transformers
    - tqdm
    - ftfy