name: knn-memory-clipcap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip=23.0.1
  - pytorch-cuda=11.8
  - pytorch=2.0.0
  - torchvision=0.15.1
  - pip:
    - ruff
    - transformers
    - tqdm
    - ftfy
    - jupyter
    - scikit-learn
    - scikit-image
    - git+https://github.com/openai/CLIP.git
    - einops>=0.6
    - einops_exts
    - filelock
    - joblib
    - faiss-gpu
    - numpy
