[tool.ruff]
ignore = ["C901", "E501", "E741", "W605"]
select = ["E", "F", "I", "W", "N", "D", "S"]
fixable = ["E", "F", "I", "W", "D"]

# Same as Black.
line-length = 88

# Assume Python 3.10.
target-version = "py310"

[tool.ruff.pydocstyle]
convention = "google"

# Ignore import violations in all `__init__.py` files.
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.isort]
lines-after-imports = 2